-- Robert Salon App 1.1 - beheer, klantdossiers, foto’s en betalingsregistratie
-- Voer dit HELE bestand één keer uit in Supabase > SQL Editor.
--
-- Belangrijk:
-- 1) Maak daarna in Supabase Authentication een gebruiker voor Robert.
-- 2) Onderaan staat de query waarmee je dat account de owner-rol geeft.
-- 3) De tijdelijke anon-leesrechten op klanten/afspraken worden hier weer dichtgezet.

begin;

alter table public.services enable row level security;
alter table public.customers enable row level security;
alter table public.appointments enable row level security;

alter table public.customers
  add column if not exists notes text not null default '';

alter table public.appointments
  add column if not exists consent_received boolean not null default false;

alter table public.appointments
  add column if not exists internal_notes text not null default '';

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'staff')),
  created_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  amount numeric(10,2) not null check (amount > 0),
  kind text not null default 'other'
    check (kind in ('deposit', 'final', 'other')),
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'failed', 'cancelled', 'refunded')),
  provider text not null default 'manual',
  provider_payment_id text,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.payments enable row level security;

create unique index if not exists one_paid_deposit_per_appointment
on public.payments(appointment_id)
where kind = 'deposit' and status = 'paid';

create table if not exists public.customer_photos (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete set null,
  storage_path text not null unique,
  photo_type text not null default 'result'
    check (photo_type in ('reference', 'design', 'before', 'result', 'healed')),
  caption text not null default '',
  created_at timestamptz not null default now()
);

alter table public.customer_photos enable row level security;

-- Helper: alleen ingelogde users met role=owner.
create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid()
      and ur.role = 'owner'
  );
$$;

revoke all on function public.is_owner() from public;
grant execute on function public.is_owner() to authenticated;

-- De app mag alleen actieve/boekbare diensten publiek zien.
drop policy if exists "Public can read bookable services" on public.services;
create policy "Public can read bookable services"
on public.services
for select
to anon, authenticated
using (active = true and bookable = true);

drop policy if exists "Owner can read all services" on public.services;
create policy "Owner can read all services"
on public.services
for select
to authenticated
using (public.is_owner());

-- Een ingelogde user mag alleen zijn/haar eigen rolrecord lezen.
drop policy if exists "Users can read own role" on public.user_roles;
create policy "Users can read own role"
on public.user_roles
for select
to authenticated
using (user_id = auth.uid());

-- Oude/tijdelijke prototypepolicies opruimen.
drop policy if exists "Temporary anon read customers" on public.customers;
drop policy if exists "Temporary anon read appointments" on public.appointments;
drop policy if exists "Public can read customers" on public.customers;
drop policy if exists "Public can read appointments" on public.appointments;

-- Owner policies voor persoonsgegevens en beheer.
drop policy if exists "Owner manages customers" on public.customers;
create policy "Owner manages customers"
on public.customers
for all
to authenticated
using (public.is_owner())
with check (public.is_owner());

drop policy if exists "Owner manages appointments" on public.appointments;
create policy "Owner manages appointments"
on public.appointments
for all
to authenticated
using (public.is_owner())
with check (public.is_owner());

drop policy if exists "Owner manages payments" on public.payments;
create policy "Owner manages payments"
on public.payments
for all
to authenticated
using (public.is_owner())
with check (public.is_owner());

drop policy if exists "Owner manages customer photos" on public.customer_photos;
create policy "Owner manages customer photos"
on public.customer_photos
for all
to authenticated
using (public.is_owner())
with check (public.is_owner());

-- Directe anon-toegang tot persoonlijke tabellen dichtzetten.
revoke all on table public.customers from anon;
revoke all on table public.appointments from anon;
revoke all on table public.payments from anon;
revoke all on table public.customer_photos from anon;
revoke all on table public.user_roles from anon;

grant usage on schema public to anon, authenticated;
grant select on public.services to anon, authenticated;

grant select on public.user_roles to authenticated;
grant select, insert, update, delete on public.customers to authenticated;
grant select, insert, update, delete on public.appointments to authenticated;
grant select, insert, update, delete on public.payments to authenticated;
grant select, insert, update, delete on public.customer_photos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Veilige publieke afspraakaanvraag.
create or replace function public.create_appointment_request(
  p_name text,
  p_email text,
  p_phone text,
  p_service_id bigint,
  p_starts_at timestamptz,
  p_idea text,
  p_placement text,
  p_consent_complete boolean
)
returns table (
  appointment_id bigint,
  customer_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer_id bigint;
  v_appointment_id bigint;
begin
  if not exists (
    select 1
    from public.services s
    where s.id = p_service_id
      and s.active = true
      and s.bookable = true
  ) then
    raise exception 'Deze behandeling is niet boekbaar.';
  end if;

  select c.id
  into v_customer_id
  from public.customers c
  where lower(trim(c.email)) = lower(trim(p_email))
  order by c.id
  limit 1;

  if v_customer_id is null then
    insert into public.customers (name, email, phone)
    values (trim(p_name), lower(trim(p_email)), trim(p_phone))
    returning id into v_customer_id;
  else
    update public.customers
    set name = trim(p_name),
        phone = trim(p_phone)
    where id = v_customer_id;
  end if;

  insert into public.appointments (
    customer_id,
    service_id,
    starts_at,
    idea,
    placement,
    consent_complete,
    consent_received,
    deposit_paid,
    status
  )
  values (
    v_customer_id,
    p_service_id,
    p_starts_at,
    trim(p_idea),
    trim(p_placement),
    coalesce(p_consent_complete, false),
    false,
    false,
    'requested'
  )
  returning id into v_appointment_id;

  return query select v_appointment_id, v_customer_id;
end;
$$;

revoke all on function public.create_appointment_request(
  text, text, text, bigint, timestamptz, text, text, boolean
) from public;

grant execute on function public.create_appointment_request(
  text, text, text, bigint, timestamptz, text, text, boolean
) to anon, authenticated;

-- Bestaande betaalde aanbetalingen migreren naar payments, indien nodig.
insert into public.payments (
  appointment_id,
  amount,
  kind,
  status,
  provider,
  paid_at
)
select
  a.id,
  s.deposit_amount,
  'deposit',
  'paid',
  'legacy',
  now()
from public.appointments a
join public.services s on s.id = a.service_id
where a.deposit_paid = true
  and coalesce(s.deposit_amount, 0) > 0
  and not exists (
    select 1
    from public.payments p
    where p.appointment_id = a.id
      and p.kind = 'deposit'
      and p.status = 'paid'
  );

-- Privé Storage-bucket voor klantfoto's.
insert into storage.buckets (id, name, public)
values ('customer-photos', 'customer-photos', false)
on conflict (id) do update set public = false;

drop policy if exists "Owner reads customer photos storage" on storage.objects;
create policy "Owner reads customer photos storage"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'customer-photos'
  and public.is_owner()
);

drop policy if exists "Owner uploads customer photos storage" on storage.objects;
create policy "Owner uploads customer photos storage"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'customer-photos'
  and public.is_owner()
);

drop policy if exists "Owner updates customer photos storage" on storage.objects;
create policy "Owner updates customer photos storage"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'customer-photos'
  and public.is_owner()
)
with check (
  bucket_id = 'customer-photos'
  and public.is_owner()
);

drop policy if exists "Owner deletes customer photos storage" on storage.objects;
create policy "Owner deletes customer photos storage"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'customer-photos'
  and public.is_owner()
);

commit;

-- ============================================================
-- OWNER ACCOUNT TOEKENNEN
-- ============================================================
-- Maak EERST in Supabase > Authentication > Users een account voor Robert.
-- Vervang daarna hieronder het e-mailadres en voer alleen deze query uit:
--
-- insert into public.user_roles (user_id, role)
-- select id, 'owner'
-- from auth.users
-- where lower(email) = lower('ROBERT_EMAIL_HIER')
-- on conflict (user_id) do update set role = excluded.role;
--
-- Controle:
-- select u.email, r.role
-- from auth.users u
-- join public.user_roles r on r.user_id = u.id;
